const acehController = require('../controllers/acehController')
const baliController = require('../controllers/baliController')
const bangkaBelitungController = require('../controllers/bangkaBelitungController')
const bantenController = require('../controllers/bantenController')
const bengkuluController = require('../controllers/bengkuluController')
const dkiJakartaController = require('../controllers/dkiJakartaController')
const gorontaloController = require('../controllers/gorontaloController')
const jabarController = require('../controllers/jabarController')
const jambiController = require('../controllers/jambiController')
const jatengController = require('../controllers/jatengController')
const jatimController = require('../controllers/jatimController')
const kalbarController = require('../controllers/kalbarController')
const kalselController = require('../controllers/kalselController')
const kaltengController = require('../controllers/kaltengController')
const kaltimController = require('../controllers/kaltimController')
const kalutController = require('../controllers/kalutController')
const kepRiauController = require('../controllers/kepRiauController')
const lampungController = require('../controllers/lampungController')
const malukuController = require('../controllers/malukuController')
const malukuUtaraController = require('../controllers/malukuUtaraController')
const ntbController = require('../controllers/ntbController')
const nttController = require('../controllers/nttController')
const papuaBaratController = require('../controllers/papuaBaratController')
const papuaController = require('../controllers/papuaController')
const riauController = require('../controllers/riauController')
const sulbarController = require('../controllers/sulbarController')
const sulselController = require('../controllers/sulselController')
const sultengController = require('../controllers/sultengController')
const sulutController = require('../controllers/sulutController')
const yogyakartaController = require('../controllers/yogyakartaController')
const sumbarController = require('../controllers/sumbarController')
const sumselController = require('../controllers/sumselController')
const sumutController = require('../controllers/sumutController')
const sultenggaraController = require('../controllers/sultenggaraController')

const router = require('express').Router()

router.get('/', (req, res) => {
  res.status(200).json({message : 'Data Berasal Dari BMKG'})
})


router.get('/aceh', acehController)
router.get('/bali', baliController)
router.get('/bangka-belitung', bangkaBelitungController)
router.get('/banten', bantenController)
router.get('/bengkulu', bengkuluController)
router.get('/yogyakarta', yogyakartaController)
router.get('/dki-jakarta', dkiJakartaController)
router.get('/gorontalo', gorontaloController)
router.get('/jambi', jambiController)
router.get('/jawa-barat', jabarController)
router.get('/jawa-tengah', jatengController)
router.get('/jawa-timur', jatimController)
router.get('/kalimantan-barat', kalbarController)
router.get('/kalimantan-selatan', kalselController)
router.get('/kalimantan-tengah', kaltengController)
router.get('/kalimantan-timur', kaltimController)
router.get('/kalimantan-utara', kalutController)
router.get('/kepulauan-riau', kepRiauController)
router.get('/lampung', lampungController)
router.get('/maluku', malukuController)
router.get('/maluku-utara', malukuUtaraController)
router.get('/ntb', ntbController)
router.get('/ntt', nttController)
router.get('/papua', papuaController)
router.get('/papua-barat', papuaBaratController)
router.get('/riau', riauController)
router.get('/sulawesi-barat', sulbarController)
router.get('/sulawesi-selatan', sulselController)
router.get('/sulawesi-tengah', sultengController)
router.get('/sulawesi-tenggara', sultenggaraController)
router.get('/sulawesi-utara', sulutController)
router.get('/sumatera-barat', sumbarController)
router.get('/sumatera-selatan', sumselController)
router.get('/sumatera-utara', sumutController)

module.exports = router